json.success Settings.success
json.user_id @user.user_id
json.ad_id @user.ad_id
json.access_token @session.access_token
json.continuos_login_count 1
json.login_bonus 1
json.first_login_on_day 1
json.remained_point 1
json.kitty_word_newest_version 2
